[workspace]
resolver = "3"
members = ["src/*"]
default-members = ["src/gitlab-time-report-cli"]

[workspace.package]
version = "1.2.1"
edition = "2024"
rust-version = "1.88"
license = "GPL-3.0-or-later"
repository = "https://gitlab.com/gitlab-time-report/gitlab-time-report"
keywords = ["gitlab", "project-management", "time-tracking"]
categories = ["command-line-utilities", "visualization"]

[workspace.dependencies]
gitlab-time-report = { path = "src/gitlab-time-report", version = "1.2.1" }
chrono = { version = "0.4.44", default-features = false, features = ["clock"] }

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)', 'cfg(tarpaulin)'] }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
match_bool = "allow" # Personal preference
implicit_hasher = "allow" # Unnecessary for our purposes
unwrap_used = "warn" # Set to warn so we can still test with unwrap. CI will fail it anyway
