[package]
name = "gitlab-time-report-cli"
description = "A CLI wrapper around gitlab-time-report"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[lints]
workspace = true

[dependencies]
gitlab-time-report = { workspace = true, features = ["charts", "dashboard"] }
chrono = { workspace = true }
clap = { version = "4.5.60", default-features = false, features = ["std", "color", "suggestions", "error-context", "usage", "help", "derive", "env"] }
cli-table = { version = "0.5.0", default-features = false }

[dev-dependencies]
assert_cmd = { version = "2.1.2", default-features = false }
mockito = { version = "1.7.2", default-features = false }
predicates = { version = "3.1.4", default-features = false }
tempfile = { version = "3.25.0", default-features = false }
